// Generated by CoffeeScript 1.6.3
(function() {
  var ccss, fs;

  if (typeof window !== "undefined" && window !== null) {
    ccss = window.ccss = function(pairs) {
      return ccss.inline(pairs);
    };
  } else {
    ccss = exports;
  }

  ccss.inline = function(pairs) {
    var key, value;
    return ((function() {
      var _results;
      _results = [];
      for (key in pairs) {
        value = pairs[key];
        key = key.replace(/[A-Z]/g, function(s) {
          return '-' + s.toLowerCase();
        });
        _results.push(" " + key + ": " + value + ";\n");
      }
      return _results;
    })()).join('');
  };

  ccss.extend = function(object, properties) {
    var key, value;
    for (key in properties) {
      value = properties[key];
      object[key] = value;
    }
    return object;
  };

  ccss.toCSS = function(selector, pairs) {
    var child, children, declarations, key, mixin, mixins, nested, split, value, _i, _j, _len, _len1, _ref;
    declarations = '';
    nested = {};
    if (mixins = pairs.mixins, pairs) {
      delete pairs.mixins;
      _ref = [].concat(mixins);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mixin = _ref[_i];
        ccss.extend(pairs, mixin);
      }
    }
    for (key in pairs) {
      value = pairs[key];
      if (typeof value === 'object') {
        children = [];
        split = key.split(/\s*,\s*/);
        for (_j = 0, _len1 = split.length; _j < _len1; _j++) {
          child = split[_j];
          children.push("" + selector + " " + child);
        }
        nested[children.join(',')] = value;
      } else {
        key = key.replace(/[A-Z]/g, function(s) {
          return '-' + s.toLowerCase();
        });
        declarations += "  " + key + ": " + value + ";\n";
      }
    }
    declarations && (css += "" + selector + " {\n" + declarations + "}\n");
    return ccss.render(nested);
  };

  ccss.render = function(rules) {
    var pairs, selector;
    return ((function() {
      var _results;
      _results = [];
      for (selector in rules) {
        pairs = rules[selector];
        _results.push(ccss.toCSS(selector, pairs));
      }
      return _results;
    })()).join('');
  };

  if (!window) {
    fs = require('fs');
    ccss.compileFile = function(infile, outfile) {
      var css, rules;
      rules = require(process.cwd() + '/' + infile);
      css = ccss.render(rules);
      outfile || (outfile = infile.replace(/coffee$/, 'css'));
      return fs.writeFileSync(outfile, css);
    };
  }

}).call(this);
